name = "TickDataPipeline"
uuid = "1321d1ed-360f-4df0-b264-cb3ad27dd90d"
authors = ["Keith <ceo@bytezoom.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.9, 1.10, 1.11"
Dates = "1"
TOML = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
