# TickDataPipeline Configuration - AMC Encoder Example
# This configuration uses the AMC (Amplitude-Modulated Continuous Carrier) encoder
# designed for Fibonacci filter bank compatibility and harmonic elimination

pipeline_name = "amc_example"
description = "Example configuration with AMC encoder (harmonic elimination)"
version = "1.0"
tick_file_path = "data/raw/YM 06-25.Last.txt"

[signal_processing]
# Encoder selection: "amc", "cpm", or "hexad16"
# - "amc": Amplitude-Modulated Continuous Carrier (harmonic elimination, filter-compatible)
# - "cpm": Continuous Phase Modulation (frequency modulation)
# - "hexad16": 16-phase discrete rotation (legacy, produces harmonics)
encoder_type = "amc"

# CPM-specific parameters (not used when encoder_type = "amc")
cpm_modulation_index = 0.5  # h=0.5 (MSK characteristics)
cpm_lut_size = 1024          # 1024-entry LUT (only size currently supported)

# AMC-specific parameters (only used when encoder_type = "amc")
amc_carrier_period = 16.0    # Carrier period in ticks (16 ticks = Ï€/8 rad/tick, HEXAD16-compatible)
amc_lut_size = 1024          # 1024-entry LUT (shares CPM_LUT_1024, only size currently supported)

# AGC parameters
agc_alpha = 0.125           # AGC smoothing factor (1/8)
agc_min_scale = 4           # Minimum AGC scale
agc_max_scale = 50          # Maximum AGC scale

# Winsorization and validation
winsorize_delta_threshold = 10  # Raw delta clipping (clips top 0.5% of deltas)
min_price = 36600               # Minimum valid price
max_price = 43300               # Maximum valid price
max_jump = 50                   # Maximum allowed price jump

[flow_control]
delay_ms = 0.0  # No delay (full speed processing)

[channels]
priority_buffer_size = 4096    # Buffer size for priority consumer
standard_buffer_size = 2048    # Buffer size for standard consumers

[performance]
target_latency_us = 500        # Target processing latency (microseconds)
max_latency_us = 1000          # Maximum acceptable latency (microseconds)
target_throughput_tps = 10000.0  # Target throughput (ticks per second)
